const sehirler = [
  { isim: "istanbul", isimler: ["istanbul", "ıstanbul"] },
  { isim: "ankara", isimler: ["ankara"] },
  { isim: "izmir", isimler: ["izmir"] },
  { isim: "adana", isimler: ["adana"] },
  { isim: "adıyaman", isimler: ["adıyaman", "adiyaman"] },
  { isim: "afyonkarahisar", isimler: ["afyonkarahisar", "afyon"] },
  { isim: "ağrı", isimler: ["ağrı", "agri"] },
  { isim: "aksaray", isimler: ["aksaray"] },
  { isim: "amasya", isimler: ["amasya"] },
  { isim: "antalya", isimler: ["antalya"] },
  { isim: "ardahan", isimler: ["ardahan"] },
  { isim: "artvin", isimler: ["artvin"] },
  { isim: "aydın", isimler: ["aydın", "aydin"] },
  { isim: "balıkesir", isimler: ["balıkesir"] },
  { isim: "bartın", isimler: ["bartın"] },
  { isim: "batman", isimler: ["batman"] },
  { isim: "bayburt", isimler: ["bayburt"] },
  { isim: "bilecik", isimler: ["bilecik"] },
  { isim: "bingöl", isimler: ["bingöl"] },
  { isim: "bitlis", isimler: ["bitlis"] },
  { isim: "bolu", isimler: ["bolu"] },
  { isim: "burdur", isimler: ["burdur"] },
  { isim: "bursa", isimler: ["bursa"] },
  { isim: "çanakkale", isimler: ["çanakkale", "canakkale"] },
  { isim: "çankırı", isimler: ["çankırı", "cankiri"] },
  { isim: "çorum", isimler: ["çorum"] },
  { isim: "denizli", isimler: ["denizli"] },
  { isim: "diyarbakır", isimler: ["diyarbakır", "diyarbekir", "diyarbakir"] },
  { isim: "düzce", isimler: ["düzce"] },
  { isim: "edirne", isimler: ["edirne"] },
  { isim: "elazığ", isimler: ["elazığ", "elazig"] },
  { isim: "erzincan", isimler: ["erzincan"] },
  { isim: "erzurum", isimler: ["erzurum"] },
  { isim: "eskişehir", isimler: ["eskişehir"] },
  { isim: "gaziantep", isimler: ["gaziantep"] },
  { isim: "giresun", isimler: ["giresun"] },
  { isim: "gümüşhane", isimler: ["gümüşhane"] },
  { isim: "hakkari", isimler: ["hakkari", "hakkarı"] },
  { isim: "hatay", isimler: ["hatay", "antakya"] },
  { isim: "ığdır", isimler: ["ığdır", "iğdır"] },
  { isim: "ısparta", isimler: ["ısparta", "isparta"] },
  { isim: "kahramanmaraş", isimler: ["kahramanmaraş"] },
  { isim: "karabük", isimler: ["karabük"] },
  { isim: "karaman", isimler: ["karaman"] },
  { isim: "kars", isimler: ["kars"] },
  { isim: "kastamonu", isimler: ["kastamonu"] },
  { isim: "kayseri", isimler: ["kayseri"] },
  { isim: "kırıkkale", isimler: ["kırıkkale"] },
  { isim: "kırklareli", isimler: ["kırklareli"] },
  { isim: "kırşehir", isimler: ["kırşehir"] },
  { isim: "kilis", isimler: ["kilis"] },
  { isim: "kocaeli", isimler: ["kocaeli", "izmit"] },
  { isim: "konya", isimler: ["konya"] },
  { isim: "kütahya", isimler: ["kütahya"] },
  { isim: "malatya", isimler: ["malatya"] },
  { isim: "manisa", isimler: ["manisa"] },
  { isim: "mardin", isimler: ["mardin"] },
  { isim: "mersin", isimler: ["mersin", "içel"] },
  { isim: "muğla", isimler: ["muğla"] },
  { isim: "muş", isimler: ["muş"] },
  { isim: "nevşehir", isimler: ["nevşehir"] },
  { isim: "niğde", isimler: ["niğde"] },
  { isim: "ordu", isimler: ["ordu"] },
  { isim: "osmaniye", isimler: ["osmaniye"] },
  { isim: "rize", isimler: ["rize"] },
  { isim: "sakarya", isimler: ["sakarya", "adapazarı"] },
  { isim: "samsun", isimler: ["samsun"] },
  { isim: "siirt", isimler: ["siirt"] },
  { isim: "sinop", isimler: ["sinop"] },
  { isim: "sivas", isimler: ["sivas"] },
  { isim: "şırnak", isimler: ["şırnak"] },
  { isim: "tekirdağ", isimler: ["tekirdağ"] },
  { isim: "tokat", isimler: ["tokat"] },
  { isim: "trabzon", isimler: ["trabzon"] },
  { isim: "tunceli", isimler: ["tunceli"] },
  { isim: "şanlıurfa", isimler: ["şanlıurfa"] },
  { isim: "uşak", isimler: ["uşak"] },
  { isim: "van", isimler: ["van"] },
  { isim: "yalova", isimler: ["yalova"] },
  { isim: "yozgat", isimler: ["yozgat"] },
  { isim: "zonguldak", isimler: ["zonguldak"] },
];

export default sehirler;
